"""gpx path and route points added to route

Revision ID: a4a3d2ecec72
Revises: a6da49d9c23d
Create Date: 2025-01-01 17:27:35.305016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4a3d2ecec72'
down_revision: Union[str, None] = 'a6da49d9c23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('gpx_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('routes', sa.Column('route_points', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'route_points')
    op.drop_column('routes', 'gpx_file_path')
    # ### end Alembic commands ###
