"""route points column added

Revision ID: a8393ff27d9f
Revises: 03d820253ce3
Create Date: 2024-12-30 11:43:10.916878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8393ff27d9f"
down_revision: Union[str, None] = "03d820253ce3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "komoot_difficulties", "grade", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_difficulties",
        "explanation_technical",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "komoot_difficulties",
        "explanation_fitness",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "komoot_path_points",
        "lat",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_path_points",
        "lng",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_path_points", "index", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("komoot_routes", sa.Column("route_points", sa.JSON(), nullable=True))
    op.alter_column("komoot_routes", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("komoot_routes", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "komoot_routes", "status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_routes", "date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "komoot_routes", "kcal_active", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_routes", "kcal_resting", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_routes",
        "distance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_routes", "duration", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_routes",
        "elevation_up",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_routes",
        "elevation_down",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_routes", "sport", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_routes", "query", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_routes", "constitution", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_routes",
        "changed_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "komoot_routes",
        "potential_route_update",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "komoot_segments", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_segments", "from_index", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_segments", "to_index", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "komoot_start_points",
        "lat",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_start_points",
        "lng",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_start_points",
        "alt",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_surface_summaries", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_surface_summaries",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "komoot_tour_information", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_way_type_summaries", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "komoot_way_type_summaries",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "komoot_way_type_summaries",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_way_type_summaries", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "komoot_tour_information", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "komoot_surface_summaries",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_surface_summaries", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "komoot_start_points",
        "alt",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_start_points",
        "lng",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_start_points",
        "lat",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_segments", "to_index", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_segments", "from_index", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_segments", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "komoot_routes",
        "potential_route_update",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "komoot_routes",
        "changed_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "komoot_routes", "constitution", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("komoot_routes", "query", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("komoot_routes", "sport", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "komoot_routes",
        "elevation_down",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_routes",
        "elevation_up",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_routes", "duration", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_routes",
        "distance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_routes", "kcal_resting", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_routes", "kcal_active", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_routes", "date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "komoot_routes", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("komoot_routes", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("komoot_routes", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("komoot_routes", "route_points")
    op.alter_column(
        "komoot_path_points", "index", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "komoot_path_points",
        "lng",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_path_points",
        "lat",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "komoot_difficulties",
        "explanation_fitness",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "komoot_difficulties",
        "explanation_technical",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "komoot_difficulties", "grade", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
