"""sport changed to enum

Revision ID: b2eb9e602720
Revises: fe2ba2c2b9bd
Create Date: 2025-01-01 21:00:48.628128

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from models.models import SportType

# revision identifiers, used by Alembic.
revision: str = "b2eb9e602720"
down_revision: Union[str, None] = "fe2ba2c2b9bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    SportType.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("routes_sport_id_fkey", "routes", type_="foreignkey")
    op.drop_table("sports")
    op.add_column(
        "routes",
        sa.Column(
            "sport",
            SportType,
            nullable=True,
        ),
    )
    op.drop_column("routes", "sport_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routes",
        sa.Column("sport_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "routes_sport_id_fkey", "routes", "sports", ["sport_id"], ["id"]
    )
    op.drop_column("routes", "sport")
    op.create_table(
        "sports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="sports_pkey"),
    )
    # ### end Alembic commands ###
    SportType.drop(op.get_bind(), checkfirst=True)
