"""route points removed from komoot route

Revision ID: fe2ba2c2b9bd
Revises: a4a3d2ecec72
Create Date: 2025-01-01 18:06:25.163953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe2ba2c2b9bd'
down_revision: Union[str, None] = 'a4a3d2ecec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('komoot_routes', 'route_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('komoot_routes', sa.Column('route_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
