"""improve_route_structure

Revision ID: improve_route_structure
Revises: c2f380f81403
Create Date: 2024-03-21 20:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "improve_route_structure"
down_revision: Union[str, None] = "c2f380f81403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add indexes for better query performance
    op.create_index("ix_routes_sport", "routes", ["sport"])
    op.create_index("ix_routes_distance", "routes", ["distance"])
    op.create_index("ix_routes_komoot_id", "routes", ["komoot_id"])

    # Add constraints for better data integrity
    op.create_check_constraint(
        "check_route_distance_positive", "routes", "distance >= 0"
    )

    # Add comment to route_points column for better documentation
    op.execute(
        """
        COMMENT ON COLUMN routes.route_points IS 'Array of [lat, lng] coordinates representing the route path'
    """
    )

    # Add comment to sport column for better documentation
    op.execute(
        """
        COMMENT ON COLUMN routes.sport IS 'Type of sport for this route (race_bike, mountain_bike, gravel_bike, touring_bike, hike, run)'
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove indexes
    op.drop_index("ix_routes_sport")
    op.drop_index("ix_routes_distance")
    op.drop_index("ix_routes_komoot_id")

    # Remove constraints
    op.drop_constraint("check_route_distance_positive", "routes")

    # Remove comments
    op.execute(
        """
        COMMENT ON COLUMN routes.route_points IS NULL
    """
    )
    op.execute(
        """
        COMMENT ON COLUMN routes.sport IS NULL
    """
    )

    # ### end Alembic commands ###
